version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:4.0.2-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password

  gate:
    container_name: gate
    build:
      context: ./services/gate
    depends_on:
      rabbitmq:
        condition: service_healthy

  permit:
    container_name: permit
    build:
      context: ./services/permit
    depends_on:
      rabbitmq:
        condition: service_healthy