services:
  rabbitmq:
    image: rabbitmq:4.0.2-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    command: "/bin/bash -c \"rabbitmq-plugins enable --offline rabbitmq_mqtt; rabbitmq-server\""
    environment:
      RABBITMQ_DEFAULT_USER: root
      RABBITMQ_DEFAULT_PASS: root
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      start_period: 10s
      interval: 5s
      timeout: 5s
      retries: 5

  eureka:
    container_name: eureka
    build:
      context: ./infrastructure/service_registry
    ports:
      - "8761:8761"
    healthcheck:
      test: curl -f http://localhost:8761
      start_period: 3s
      interval: 1s
      timeout: 1s
      retries: 10

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - gate
      - violation
      - permit
      - payment
      - visitor

  gate:
    container_name: gate
    build:
      context: ./service/gate
    expose:
      - "8081"
    environment:
      - SERVER_PORT=8081
    depends_on:
      rabbitmq:
        condition: service_healthy
      eureka:
        condition: service_healthy

  violation:
    container_name: violation
    build:
      context: ./service/violation
    expose:
      - "8082"
    environment:
      - SERVER_PORT=8082
    depends_on:
      rabbitmq:
        condition: service_healthy
      eureka:
        condition: service_healthy

  permit:
    container_name: permit
    build:
      context: ./service/permit
    expose:
      - "8083"
    environment:
      - SERVER_PORT=8083
    depends_on:
      rabbitmq:
        condition: service_healthy
      eureka:
        condition: service_healthy

  payment:
    container_name: payment
    build:
      context: ./service/payment
    expose:
      - "8084"
    environment:
      - SERVER_PORT=8084
    depends_on:
      rabbitmq:
        condition: service_healthy
      eureka:
        condition: service_healthy

  visitor:
    container_name: visitor
    build:
      context: ./service/visitor_access
    expose:
      - "8085"
    environment:
      - SERVER_PORT=8085
    depends_on:
      rabbitmq:
        condition: service_healthy
      eureka:
        condition: service_healthy