version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:4.0.2-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: root
      RABBITMQ_DEFAULT_PASS: root
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      start_period: 5s
      interval: 1s
      timeout: 1s
      retries: 10

#  gate:
#    container_name: gate
#    build:
#      context: ./service/gate
#    depends_on:
#      rabbitmq:
#        condition: service_healthy
#
#  permit:
#    container_name: permit
#    build:
#      context: ./service/permit
#    depends_on:
#      rabbitmq:
#        condition: service_healthy