spring:
  rabbitmq:
    host: localhost
    port: 5672

  datasource:
    url: jdbc:h2:mem:gatedb
  h2.console:
    enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

info:
  application:
    name: '@project.name@ (local deployment)'