spring:
  application:
    name: gate

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: root
    password: root

app:
  custom:
    messaging:
      transponder: transponderReaderExchange
      gate: gateOpenRequestExchange
      visitor-entry-request-exchange: visitorEntryRequestExchange
