spring:
  application:
    name: gate

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: root
    password: root

app:
  custom:
    messaging:
      gate:
        routing-key: gate.%s.command
        exchange: gateOpenRequestExchange
      visitor:
        exchange:
          request: gateToVisitorExchange
      permit:
        exchange:
          request: gateToPermitExchange
      response:
        exchange: toGateResultExchange
