spring:
  datasource:
    url: jdbc:h2:mem:ticketDB
  h2.console:
    enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop
  sql:
    init:
      mode: always
  rabbitmq:
    host: localhost
    port: 5672

  # 服务器配置
server:
  port: 9081 # 服务器监听的端口号为 9080

