spring:
  application:
    name: payment

  ## ?????
  datasource:
    username: root # ???????????? H2 ?????? "sa"
    password: root # ???????H2 ????????
    driverClassName: org.h2.Driver # ???????????? H2 ???

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect # ???? H2 ???????? Hibernate ????? H2 ??
    defer-datasource-initialization: true # ???????????????????????

## ??????
logging.level:
  ca.mcmaster.cas735.tmt.customers:
    adapter:  DEBUG # ?????????? INFO???????? DEBUG
    business: DEBUG # ????????? INFO???????? DEBUG

# ?????
server:
  port: 9090 # ?????????????? 9090


#TODO:????????. Eureka?????,???Eureka?????
# ?? Eureka ?????????????
eureka:
  client:
    healthcheck:
      enabled: true # ????????????????????? Eureka ????
