package ca.mcmaster.cas735.acmepark.visitor_access.ports.required;

import ca.mcmaster.cas735.acmepark.visitor_access.business.entities.Visitor;
import org.springframework.data.jpa.repository.JpaRepository;

import java.util.Optional;

public interface VisitorDataRepository extends JpaRepository<Visitor, Long> {

    /** Methods are auto-generated by JPA based on name conventions:
     * Source: https://docs.spring.io/spring-data/jpa/reference/jpa/query-methods.html
     **/

    // 根据车牌号查询 Visitor
    Optional<Visitor> findByLicensePlate(String licensePlate);
}