spring:
  application:
    name: permit

  rabbitmq:
    username: root
    password: root

  datasource:
    username: root
    password: root
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect # 指定 H2 数据库所需的 Hibernate 方言
    defer-datasource-initialization: true # 延迟数据源初始化，确保数据库在 JPA 初始化之前已经设置好
    hibernate:
      ddl-auto: create-drop

  sql:
    init:
      mode: always
      data-locations: classpath:data.sql

app:
  custom:
    messaging:
      gate-to-permit-exchange: gateToPermitExchange
      permit-to-gate-exchange: toGateResultExchange
      payment-request-exchange: paymentRequestExchange
      payment-response-permit-exchange: paymentResultPermitExchange

eureka:
  client:
    healthcheck:
      enabled: true

info:
  application:
    description: '@project.description@'
    version:     '@project.version@'