flowchart LR

    AMQPGateController([fa:fa-circle-right AMQP fa:fa-envelope<br> Gate Controller])
    AMQPTransponderReader([fa:fa-circle-right AMQP fa:fa-envelope<br> Transponder Reader])
    AMQPValidationReqSender([fa:fa-circle-right AMQP fa:fa-envelope<br> Validation Req Sender])
    AMQPValidationResultReceiver([fa:fa-circle-right AMQP fa:fa-envelope<br> Validation Result Receiver])

    subgraph "<< Gate Service >>"
        TransponderReader("<< InputPort >><br>Transponder Reader")
        PermitValidationReqReceiver("<< InputPort >><br>Validation Req Receiver")
        PermitValidationReqSender("<< OutputPort >><br>Validation Req Sender")
        GateController("<< OutputPort >><br>Gate Controller")
        GateReqHandler{{"Gate <br> Request Handler"}}
        GateResultHandler{{"Gate <br> Result Handler"}}
    end

    AMQPTransponderReader -- Transponder ID --> TransponderReader
    AMQPValidationResultReceiver -- Valid/Invalid --> PermitValidationReqReceiver
    PermitValidationReqSender -- Transponder ID --> AMQPValidationReqSender
    GateController -- True/False --> AMQPGateController

    TransponderReader -. offered .-> GateReqHandler -. required .-> PermitValidationReqSender
    PermitValidationReqReceiver -. offered .-> GateResultHandler -. required .-> GateController
