flowchart LR

    AMQPPaymentReqListener([fa:fa-circle-right AMQP fa:fa-envelope<br> Payment Req Listener])
    AMQPPaymentResultSender([fa:fa-circle-right AMQP fa:fa-envelope<br> Payment Result Sender])
    H2Database([fa:fa-circle-right SQL fa:fa-database<br> H2 Database])
    ViolationService([fa:fa-circle-right REST fa:fa-server<br> Violation Service])

    subgraph "<< Payment Service >>"
        PaymentProcessor("<< InputPort >><br> Payment Processor")
        PaymentResultSender("<< OutputPort >><br> Payment Result Sender")
        PaymentDBAccessor("<< Bidirectional Port >><br> Database Accessor")
        PAYMENT_SERVICE{{"Payment <br> Service"}}
    end

    AMQPPaymentReqListener -- Payment Request --> PaymentProcessor
    PaymentProcessor -- Fine Information Request --> ViolationService
    ViolationService -- Fine Information Response --> PaymentProcessor
    PaymentDBAccessor -- Access --> H2Database
    PaymentResultSender -- Success/Failure --> AMQPPaymentResultSender

    PaymentProcessor -. offered .-> PAYMENT_SERVICE
    PAYMENT_SERVICE -. required .-> PaymentResultSender
    PAYMENT_SERVICE -. required .-> PaymentDBAccessor
    PAYMENT_SERVICE -. required .-> ViolationService
