flowchart LR
    Transponder([fa:fa-id-card Transponder Reader])
    RabbitMQ([fa:fa-server RabbitMQ])
    GateService([fa:fa-cogs Gate Service])
    PermitService([fa:fa-cogs Permit Service])
    Cassandra([fa:fa-database Cassandra])
    Transponder --> RabbitMQ --> GateService
    GateService --> RabbitMQ --> PermitService
    PermitService --> RabbitMQ --> Transponder
    PermitService <--> Cassandra