flowchart LR
    Transponder([fa:fa-id-card Transponder Reader])
    RabbitMQ([fa:fa-server RabbitMQ])
    GateService([fa:fa-cogs Gate Service])
    PermitService([fa:fa-cogs Permit Service])
    VisitorService([fa:fa-cogs Visitor Service])
    ViolationService([fa:fa-cogs Violation Service])
    PaymentService([fa:fa-cogs Payment Service])

    H2([fa:fa-database H2])

    Transponder <--> RabbitMQ
    GateService <--> RabbitMQ
    PermitService <--> RabbitMQ
    VisitorService <--> RabbitMQ
    ViolationService <--> RabbitMQ
    PaymentService <--> RabbitMQ