spring:
  application:
    name: visitor_access

  rabbitmq:
    username: root
    password: root

  datasource:
    username: root
    password: root
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop

  sql:
    init:
      mode: always
      data-locations: classpath:data.sql


logging:
  level:
    ca.mcmaster.cas735.acmepark.visitor_access:
      adapter: INFO
      application: INFO
      org.springframework.boot.sql.init: INFO


app:
  custom:
    messaging:
      gate-to-visitor-exchange: gateToVisitorExchange
      visitor-to-gate-exchange: toGateResultExchange
      payment-request-exchange: paymentRequestExchange
      payment-response-visitor-exchange: paymentResultVisitorExchange

eureka:
  client:
    healthcheck:
      enabled: true

info:
  application:
    description: '@project.description@'
    version:     '@project.version@'