spring:
  rabbitmq:
    host: localhost
    port: 5672

app:
  custom:
    mqtt:
      host: localhost
info:
  application:
    name: '@project.name@ (local deployment)'

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
