spring:
  application:
    name: visitor_access

  rabbitmq:
    username: admin
    password: root

# ??????
logging:
  level:
    ca.mcmaster.cas735.acmepark.visitor_access:
      adapter: INFO # ??????????????? DEBUG ?????????
      application: INFO # ????????

# ?????
server:
  port: 9080 # ??????

# ???????
app:
  custom:
    messaging:
      inbound-exchange-topic: visitor.exchange.topic # ?? RabbitMQ ????????
      outbound-exchange-topic: visitor.notification # ?? RabbitMQ ????????

# ??????????????????
management:
  info:
    env:
      enabled: true # ????????????????????????
  endpoints:
    web:
      exposure:
        include: info,health # ?? "info" ? "health" ?????????????????????
      base-path: /actuator # ?????????? "/actuator"??? "/actuator/health" ??????


# ????????????????????
info:
  application:
    description: '@project.description@' # ????????????????? Maven????
    version: '@project.version@' # ?????????????????

eureka:
  client:
    healthcheck:
      enabled: true